### ISSUE TITLE
Set swipe effect sensibility

### ISSUE THREAD

**Issue by RoFiks** [FrDH/jQuery.TosRUs#51]
Hi there,

I was wondering if it's possible to set the swipe sensibility? Now it feels like you have to swipe a long way before the next image is shown. I would like to make it swipe more fast. 

Hope you can help, thanks!

**Comment by mgntrn** [comment]
I agree with RobinFiks. I'm testing some plug-ins and the first thing I noticed with this one is that you have to drag way too long to swipe to the next image. It's not as intuitive as it should be.

**Comment by Denyerec** [comment]
I was about to raise this as an issue, only to discover it's already there!
When the phone is landscape, especially on large handsets like the iPhone6/6+ it's impossible to comfortably swipe the images.

Perhaps 33% would be a more sensible default ?

**Comment by FrDH** [comment]
Note there's a difference between dragging and swiping. Animating to the next image after dragging less than 50% would not be very logical. 
What differentiates dragging from swiping is handled by the Hammer plugin.  I'm not entirely sure, but think you should be able to change it's default values.

**Comment by mrlevinson** [comment]
Was anybody able to change the default values in the Hammer plugin? My client also thinks the the swiping isn't sensitive enough.

**Comment by sampraa** [comment]
I experimented little bit. Seems to me hammer.js has nothing to do with it – hammer is just saying “panright/panleft”. I found this code:
jquery.tosrus.drag.js: slides = Math.floor( ( Math.abs( _distance ) + ( slideWidth / 2 ) ) / slideWidth );
OR
jquery.tosrus.min.all.js: e=Math.floor((Math.abs(f)+s/2)/s)
Number 2 means: you have to drag an image beyond half its width to move to next/prev image.
SOLUTION:
If I tried number 1 instead, it works OK for me, as usual for android touch devices (mobile, tablet). Or you could try other value, according to your requirements.
My suggestion: to drag an image beyond half looks logically but it is not standard on nowadays device so it could be confusing for users. Number 1 is better but setting this value in configuration options would be best solution.

**Comment by FrDH** [comment]
Thank you for taking the time to find a solution :)
I'll make a configuration option for it in the next version.

**Comment by netlander** [comment]
Has this issue been addressed yet? Just about to embark on choosing a
lightbox/carousel for a site redesign and wondered if this would not be a
show stopper.

**Comment by AlvSovereign** [comment]
Sampraa

Thank you for your contribution on this.

I have made changes to my js as per your suggestion and very happy with the usability.

Thanks again

AlvSovereign

**Comment by rehand** [comment]
Would be nice if this fix could be merged into a new release.
