### ISSUE TITLE
autoplay youtube video?

### ISSUE THREAD

**Issue by frontenddevguy** [FrDH/jQuery.TosRUs#55]
I didnt see an option to configure this.
The url already has ?rel=0&amp;autoplay=1

**Comment by FrDH** [comment]
autoplay for video's is not supported. Not a bad idea though.
I'll see if I can implement it in the next release.

**Comment by JvanderHeide** [comment]
I'm currently using this:
```javascript
var videoPopups = $(".tosrus").tosrus({
	youtube: {
		maxWidth: 1080,
		imageLink: false,
	},
	vimeo: {
		maxWidth: 1080,
		imageLink: false,
	}
}).bind("opening.tos", function() {
    var $iframe = $(this).find('iframe'),
    src = $iframe.attr('src');
    $iframe.attr('src', src+"&autoplay=1");
});
```
Works like a charm :)

**Comment by FrDH** [comment]
Unfortunately this repo is no longer actively maintained due to the enormous amount of alternative slider- and lightbox plugins.
