### ISSUE TITLE
FR: Deep Linking

### ISSUE THREAD

**Issue by Denyerec** [FrDH/jQuery.TosRUs#58]
I was wondering if you had plans to add deep linking / history.js support to the tool? Thought I'd ask before I started hacking away, as it's a pretty useful feature for sending people to a particular image, especially if the thumbnail gallery in question contains a large number of images.

**Comment by FrDH** [comment]
Personally, I find deeplinking pretty irritating, so I don't have it on my TODO list. But if you'd like, you could create an add-on for this behavior.

**Comment by Denyerec** [comment]
I think Deep Linking is pretty essential if the plugin is to have use in galleries. For example, if you visit here:

http://stuff.denyerec.co.uk/venice2011/

And then decide you want to tell your friend about the picture of the bridge... There is no way to do this. Even if the files are numbered, masonry layouts make counting awkward, and in a large square-set gallery it would be impractical.

However:

http://stuff.denyerec.co.uk/venice2011/#!DSCF0764_p.jpg

Simple :)

If you have an existing add-on you can point me to so I can inspect the code to figure out how to do this I could try, though I am unlikely to be able to make an add-on that will meet your code quality requirements. Much as I would like to publicly contribute - the current deep linking on my site is a quick hack that no doubt would attract a lot of negative attention.

**Comment by JvanderHeide** [comment]
You could simply use History.js yourself and by using `.bind("opening.tos")` updating the url with the image url (or any other identifier) for instance. 
Only thing you need to do then is check for the presence of the url fragment (or identifier) on page load and trigger a click/opem on the link that matches it.

**Comment by Denyerec** [comment]
JvanderHeide, that's pretty much the solution I arrived at, it's just surprising that deeplinks are less common 'out of the box'. Nobody wants to email a link to a gallery to a colleague and tell them to "Checkout the 47th image in the gallery, it's really cool" - it's preferable to send links to the intended image itself, but retain the context of the page / gallery.  Obviously you could just send the URI to the single image file, but this then causes confusion for the average user should they wish to browse more from the gallery.

**Comment by JvanderHeide** [comment]
@Denyerec I agree :+1:

**Comment by iBobik** [comment]
@FrDH Will you accept pull request if we implement this feature as optional?

**Comment by Denyerec** [comment]
Any word on this?

**Comment by Denyerec** [comment]
I've hit this issue *again*... any word on an update?

**Comment by iBobik** [comment]
I finally used http://photoswipe.com/ - it can link to images by hashed URL and is perfectly usable on touch devices.

**Comment by FrDH** [comment]
Unfortunately this repo is no longer actively maintained due to the large amount of alternative slider- and lightbox plugins.
