### ISSUE TITLE
Setting defaults

### ISSUE THREAD

**Issue by JvanderHeide** [FrDH/jQuery.TosRUs#61]
Because I found nothing about this in the docs;
I was wondering, to set certain settings on a global scale, I'm currently using this: 
```javascript
$.tosrus.defaults.wrapper.onClick = "close";
$.tosrus.defaults.keys = $.tosrus.constants.keys;
```
Was this the intended use of the defaults or is there another way to declare global settings that's preferred?

**Comment by FrDH** [comment]
Overriding the `$.tosrus.defaults` is indead how it is intended, using the `$.tosrus.constants` isn't, but I guess there's no harm in using it.
