### ISSUE TITLE
Add TOSRUS lib to a CDN

### ISSUE THREAD

**Issue by netlander** [FrDH/jQuery.TosRUs#68]
Hey,

I want to raise his as an issue. Is there an existing hosted TOSRUS library on any content delivery network like Google Hosted Libraries or cdnjs?

Thanks

**Comment by FrDH** [comment]
Not that I'm aware of.

**Comment by tobiv** [comment]
Anyone can request an addition to cdnjs on https://github.com/cdnjs/cdnjs (preferrably in the form of a pull request).
