### ISSUE TITLE
Change settings

### ISSUE THREAD

**Issue by kpil** [FrDH/jQuery.TosRUs#70]
Hello team. i want to know if it's possible to change some settings on ΤosRUs Lightbox script.

as i see here (on section “Inline buttons and fade effect” http://tosrus.frebsite.nl/examples.php ) i want to put next/previous buttons and the close “X” button (http://www.jqueryscript.net/slider/Responsive-Touch-Optimized-jQuery-Slider-Plugin-TosRUs.html), inside of each image.

Can you tell me how to do it?

Also, i want to kwow if it’s possible “onclick” on image, to go to next image, and it is not necessary to click the “next button”.

**Comment by FrDH** [comment]
The JS is located directly below the example.

To make the slider slide to the next slide when clicking an image, you could trigger the "next" event on the wrapper when clikcing an image inside it. I guess that should work.
````javascript
var tos = $("#foo a").tosrus();
tos.on( "click", "img", function() {
   tos.trigger( "next" );
});
````

**Comment by kpil** [comment]
hello. thanks for responce. i use Responsive Lightbox wordpress plugin, can you tell me in which files should make these changes?

**Comment by AlvSovereign** [comment]
Hi kpll

I have had sucess by adding it as an inline script as the last script tags in your body element.

This ensures that this script is ran after your javascript resources have been loaded.

Hope this helps.

AlvSovereign
