### ISSUE TITLE
Youtube video has wrong size after changing size of window

### ISSUE THREAD

**Issue by sb-relaxt-at** [FrDH/jQuery.TosRUs#74]
The following steps result in a tiny Youtube video: 

* Make the browser window full size
* Open the Youtube-Slide
* Close the Youtube-Slide
* Make the browser window tiny
* Make the browser window full size again
* Open the Youtube-Slide

This issue can be reproduced in different browsers (Current Chrome-Version on MacOS, IE11, ...) using the current version (2.4.1) and the example on the official webpage.

A fix seems to be a patch for the youtube plugin in [initVideo] (https://github.com/BeSite/jQuery.TosRUs/blob/master/src/js/media/jquery.tosrus.youtube.js#L112):

```
this.nodes.$wrpr
.on( _e.opening,
    function( e )
    {
        _f.resizeRatio( $v, $s, maxWidth, maxHeight, ratio );
    }
)
```

**Comment by FrDH** [comment]
Thank you for pointing out the issue.

I think the "resizeRatio" function fired onWindowResize measures "0" for the height and width if the slide isn't opened (a hidden element does not have a measurable width or height).
The fix would be to not resize the element if it isn't visible AND to resize the element on opening (as suggested).

I'll fix this in the next version.
