### ISSUE TITLE
Browser Compatibility issues 

### ISSUE THREAD

**Issue by umairlodhi** [FrDH/jQuery.TosRUs#76]
Working fine on google chrome
but as i tested on the other browsers its not working fine like touch issues in firefox and safari
versions of the browsers are given bellow..
Firefox: 42.0 .
Safari: 5.1.7 .

please help me to sort out this issue

![firefox](https://cloud.githubusercontent.com/assets/16190728/11628008/de7a319c-9cff-11e5-8041-c14ab3769e6b.png)
![safari](https://cloud.githubusercontent.com/assets/16190728/11628007/de75dcc8-9cff-11e5-934c-95b3f2201dcf.png)

**Comment by FrDH** [comment]
The touch-gestures are handled by the Hammer.js library. Maybe it needs to be updated?
