### ISSUE TITLE
Can I add Image hover on lightbox? If yes then how can I do that? 

### ISSUE THREAD

**Issue by hassaan-rana-** [FrDH/jQuery.TosRUs#77]
I want to add caption on hover image in lightbox. Or is there any way to add custom html code in lightbox?

Actually I want to add date of image and caption both. Date of image will be on top or bottom and caption could be on hover or if not possible then below image. But there is only one option in this slider.

**Comment by hassaan-rana-** [comment]
Actually I want to add date of image and caption both. Date of image will be on top or bottom and caption could be on hover or if not possible then below image. But there is only one option in this slider.

**Comment by FrDH** [comment]
No not really. I guess you could put some HTML in the `title` attribute, but that seems like a dirty workaround.
