### ISSUE TITLE
https support for Youtube an d Vimeo

### ISSUE THREAD

**Issue by deflektor01** [FrDH/jQuery.TosRUs#78]
Tosrus' Youtube and Vimeo support in lightbox is not usable in pure https-environments, because of hard coded non-secure Urls. Most browsers block mixed secure and unsecure sources on the same page. A pitty. There was a simple solution before as a pull request, but it was not accepted for formal reasons. Would be great, if a developper could review this.

**Comment by FrDH** [comment]
Thank you for the suggestion. I'll have a look at it.

**Comment by andres314** [comment]
+1
I have to hardcode the plugin for that.
