### ISSUE TITLE
multiple galleries on same page

### ISSUE THREAD

**Issue by anarchoi** [FrDH/jQuery.TosRUs#80]
How can i have multiple galleries on the same page ? This code will open all images in the same lightbox, but i want to display only the images in the current gallery

In other words, when clicking first link, display the 2 cats images in the lightbox, and when clicking second link display the 2 others images. I don't want to display the 4 images at same time.

I know i could do this by adding more $('#lightbox a').tosrus({ in jquery, but i have 100 different galleries on the same page it would be non-sense to do this 100 times

If TosRUs can't do this i'll have to go back to slimbox :(

		<script type="text/javascript" language="javascript">
			jQuery(function( $ ) {

				//	Add a custom filter to recognize images from lorempixel (that don't end with ".jpg" or something similar)
				$.tosrus.defaults.media.image = {
					filterAnchors: function( $anchor ) {
						return $anchor.attr( 'href' ).indexOf( 'lorempixel.com' ) > -1;
					}
				};

				$('#lightbox a').tosrus({
					buttons: 'inline',
					pagination	: {
						add			: true,
						type		: 'thumbnails'
					}
				});

			});
		</script>

	</head>
	<body>

				<div id="lightbox">
					<a href="http://lorempixel.com/1200/675/cats/5/">1</a>
					<a href="http://lorempixel.com/1200/675/cats/6/"></a>
				</div>

				<div id="lightbox 2">
					<a href="http://lorempixel.com/1200/675/cats/7/">2</a>
					<a href="http://lorempixel.com/1200/675/cats/8/"></a>
				</div>

	</body>
</html>

**Comment by FrDH** [comment]
Images are grouped into a gallery based on the set of DOM elements you used to call the plugin.
For example, this will create one gallery for all images inside a `DIV.lightbox`:
````javascript
// one set of DOM elements for all anchors
$("div.lightbox a").tosrus();
````
And this will create a gallerie per `DIV.lightbox`:
````javascript
$("div.lightbox").each(function() {
    // a set of DOM elements inside each div.lightbox
    $(this).find( "a" ).tosrus();
});
````

**Comment by anarchoi** [comment]
Thanks for the reply ! But i can't get it to work :( What's wrong with my code ? Sorry for the noobish questions i'm not very good with javascript stuff

    <script type="text/javascript" language="javascript">
        jQuery(function( $ ) {

		$("div.lightbox").each(function() {
            $(this).find( "a" ).tosrus({
                buttons: 'inline',
                pagination  : {
                    add         : true,
                    type        : 'thumbnails'
                }
            });
		});

        });
    </script>
	</head>
	<body>

		<div id="lightbox">
			<a href="https://www.google.ca/logos/doodles/2016/90th-anniversary-of-the-first-demonstration-of-television-6281357497991168.2-hp.jpg">1</a>
			<a href="https://www.google.ca/logos/doodles/2016/90th-anniversary-of-the-first-demonstration-of-television-6281357497991168.2-hp.jpg"></a>
		</div>


		<div id="lightbox">
			<a href="https://www.google.ca/logos/doodles/2016/90th-anniversary-of-the-first-demonstration-of-television-6281357497991168.2-hp.jpg">2</a>
			<a href="https://www.google.ca/logos/doodles/2016/90th-anniversary-of-the-first-demonstration-of-television-6281357497991168.2-hp.jpg"></a>
		</div>

**Comment by tobiv** [comment]
You're selecting divs with a `class` "lightbox" (indicated by the dot `.` before the class name), but your actual divs have an `id` "lightbox" (that would be a `#` before the name. An `id` is only allowed once per document, by the way).
