### ISSUE TITLE
close when clicking outside of lightbox

### ISSUE THREAD

**Issue by anarchoi** [FrDH/jQuery.TosRUs#81]
i can't get the lightbox to close itself when the use clicks outside of the image even when setting the "onClick: close" option in the wrapper as explained in the documentation. Am i doing something wrong ?

	jQuery(function( $ ) {

		$('#lightbox-1 a').tosrus({
			buttons : {
			prev : true,
			next : true,
			close: true
			},
			buttons: 'inline',
			pagination	: {
				add			: true,
				type		: 'thumbnails'
			},
			wrapper : {
				onClick : close,
				classes: 'img-border'
			},
			caption : {
				add : true
			}

		});

	});
</script>

**Comment by FrDH** [comment]
`close` as a variable probably is undefined, you should make it a string `"close"`
