### ISSUE TITLE
Not working with turbolinks

### ISSUE THREAD

**Issue by ghost** [FrDH/jQuery.TosRUs#85]
Plugin works fine for the first request, but when clicking on turbolink link, doesnt work..

i do run it each time:

```
$(document).on('page:load page:fetch ready', function () {
  initSidebarImageGallery();

  function initSidebarImageGallery() {
    $(".js-gallery a").tosrus({
      slides:     {
        scale: "fill"
      },
      caption:    {
        add: true
      },
      pagination: {
        add:  true,
        type: "thumbnails"
      },
      buttons:    false
    });
  }

});
```

```
<div class="js-gallery">
  <a href="image_url"><img src="image_url" alt="image"/></a>
</div>
```

Even tried to launch it manually (in js console).
Also tried to remove the element, this plugin creates `.tos-wrapper`, before the init function.

Sidebar is re-rendered again, each time. But the plugin doesn't work anymore.

In particular: clicking on images no thing happens (meaning a href default action is canceled, but the plugin gallery popup is not shown).

Also tried to unbind all the events to the hrefs and then calling the init function - nothing.
also tried to dup (clone) the element (.js-gallery) and replacing it (meaning, creating new dom element in the same place) - nothing

Any more suggestions?

**Comment by FrDH** [comment]
I don't this'll ever work
