### ISSUE TITLE
Images thumbnail and different sizes of img.

### ISSUE THREAD

**Issue by pszafer** [FrDH/jQuery.TosRUs#88]
Hello,

It is more than enhancement than issue.
Maybe it is possible that tosrus would use srcset from img for thumbnails (the smallest img) and for photos copy srcset so loading will be more customized for all devices.
I think it seems easy to implement.

I have such object:
```
<a href="IMG_2048px.jpg"><img src="IMG_400px.jpg srcset="IMG_800 800 ...></a>
```
Maybe it is possible to do such things easily:

for thumbnails, in jquery.tosrus.pagination.js
```
case thumbnail:
if (imgsrc == anchorhref)
var imgForThumbnail = srcOfTheSmallestImg from srcSet;
var pre 	= '<a href="#" style="background-image: url(\'',
							post	= '\');"></a>';
...

```
And of course for img itself, copy all srcset from img.

Thanks in advance!

**Comment by FrDH** [comment]
That indead is a good idea, unfortunately this repo is no longer actively maintained due to the enormous amount of alternative slider- and lightbox plugins.
